/*
 * Copyright 2025 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

package com.adobe.marketing.mobile.concierge.utils.simulation

/**
 * Simulates speech-to-text transcription and conversation responses for testing purposes.
 * This class will be replaced with actual speech recognition and brand concierge integration.
 */
class SpeechSimulator {
    
    /**
     * Simulates a response from the brand concierge system.
     * 
     * @param userText The user's input text
     * @return A simulated response message
     */
    fun simulateResponse(userText: String): String {
        return "You said: '$userText'"
    }
    
    /**
     * Generates simulated transcribed text from voice input.
     * 
     * @return A randomly selected sample phrase
     */
    fun generateSimulatedTranscription(): String {
        val samplePhrases = listOf(
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "This is another mock transcription to test the speech-to-text functionality in the chat application.",
            "This is a mock transcription of a voice input. It is designed to simulate the kind of text that might be generated by a speech-to-text system."
        )
        return samplePhrases.random()
    }
    
    /**
     * Simulates transcription processing delay.
     * 
     * @return A random delay between 500ms and 2000ms
     */
    fun getSimulatedTranscriptionDelay(): Long {
        return (500..2000).random().toLong()
    }
    
    /**
     * Simulates network response delay for bot responses.
     * 
     * @return A random delay between 800ms and 1500ms
     */
    fun getSimulatedResponseDelay(): Long {
        return (800..1500).random().toLong()
    }
}
