/*
 * Copyright 2025 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

package com.adobe.marketing.mobile.concierge.chat.simulation

/**
 * Simulates speech-to-text transcription and conversation responses for testing purposes.
 * This class will be replaced with actual speech recognition and brand concierge integration.
 */
class SpeechSimulator {
    
    /**
     * Simulates a response from the brand concierge system.
     * 
     * @param userText The user's input text
     * @return A simulated response message
     */
    fun simulateResponse(userText: String): String {
        return "Thanks for your message: '$userText'"
    }
    
    /**
     * Generates simulated transcribed text from voice input.
     * 
     * @return A randomly selected sample phrase
     */
    fun generateSimulatedTranscription(): String {
        val samplePhrases = listOf(
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?",
            "This is a mock transcription of a voice input. It is designed to simulate the kind of text that might be generated by a speech-to-text system. The actual content is not important, but it should resemble natural language and be varied enough to test different scenarios in the chat application."
        )
        return samplePhrases.random()
    }
    
    /**
     * Simulates transcription processing delay.
     * 
     * @return A random delay between 500ms and 2000ms
     */
    fun getSimulatedTranscriptionDelay(): Long {
        return (500..2000).random().toLong()
    }
    
    /**
     * Simulates network response delay for bot responses.
     * 
     * @return A random delay between 800ms and 1500ms
     */
    fun getSimulatedResponseDelay(): Long {
        return (800..1500).random().toLong()
    }
}
