name: Publish Release

on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag (version) to be released (ex: 1.2.3).'
        type: string
        required: true

      create-github-release:
        description: 'Create GitHub release using tag. If the provided `tag` does not exist, it will be created.'
        type: boolean
        required: true
        default: true

      core-dependency:
        description: 'The Core dependency version in gradle.properties to be validated (ex: 1.2.3).'
        type: string
        required: true

jobs:
  publish:
    permissions:
        contents: write
    uses: adobe/aepsdk-commons/.github/workflows/android-maven-release.yml@gha-android-3.4.3
    with:
      tag: ${{ github.event.inputs.tag }}
      create-github-release: ${{ github.event.inputs.create-github-release == 'true' }}
      version-validation-paths: code/gradle.properties, code/concierge/src/phone/java/com/adobe/marketing/mobile/Concierge.java # to-do: update with actual API file
      version-validation-dependencies: Core ${{ github.event.inputs.core-dependency }} # to-do: update with the actual prod dependencies
    secrets: inherit